version: "3.7"

services:
  wait_for_healthcecks:
    image: busybox
    depends_on:
      mysql:
        condition: service_healthy
      postgres:
        condition: service_healthy

  mysql:
    image: mysql:8.0.31
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql:/var/lib/mysql:delegated
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:1.0.6
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=P1ssw0rd
    volumes:
      - sqlserver:/var/opt/mssql:delegated
    cap_add:
      - SYS_PTRACE

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres:/var/lib/postgresql/data:delegated
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql:
  sqlserver:
  postgres:
